import { count, desc, eq, sql } from "drizzle-orm";
import { Activity, Building2, FilePlus2, MailCheck, UserPlus, Users } from "lucide-react";
import Link from "next/link";

import { DeliveryTrendChart, GrowthChart } from "@/components/superadmin/admin-analytics-charts";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { db } from "@/db";
import { organization, user } from "@/db/auth-schema";
import { auditLog, emailDelivery } from "@/db/schema";

function shortDay(date: Date) { return date.toLocaleDateString("en", { month: "short", day: "numeric", timeZone: "UTC" }); }
function shortMonth(date: Date) { return date.toLocaleDateString("en", { month: "short", timeZone: "UTC" }); }

export default async function SuperadminOverview() {
  const [[users], [workspaces], [deliveries], [accepted], events, dailyRows, userGrowth, workspaceGrowth] = await Promise.all([
    db.select({ value: count() }).from(user), db.select({ value: count() }).from(organization), db.select({ value: count() }).from(emailDelivery).where(sql`${emailDelivery.createdAt} >= now() - interval '30 days'`), db.select({ value: count() }).from(emailDelivery).where(eq(emailDelivery.status, "sent")), db.select().from(auditLog).orderBy(desc(auditLog.createdAt)).limit(7),
    db.select({ day: sql<string>`date_trunc('day', ${emailDelivery.createdAt})::date::text`, status: emailDelivery.status, value: count() }).from(emailDelivery).where(sql`${emailDelivery.createdAt} >= now() - interval '13 days'`).groupBy(sql`1`, emailDelivery.status),
    db.select({ month: sql<string>`date_trunc('month', ${user.createdAt})::date::text`, value: count() }).from(user).where(sql`${user.createdAt} >= now() - interval '5 months'`).groupBy(sql`1`),
    db.select({ month: sql<string>`date_trunc('month', ${organization.createdAt})::date::text`, value: count() }).from(organization).where(sql`${organization.createdAt} >= now() - interval '5 months'`).groupBy(sql`1`),
  ]);
  const daily = Array.from({ length: 14 }, (_, index) => { const date = new Date(); date.setUTCHours(0,0,0,0); date.setUTCDate(date.getUTCDate() - (13 - index)); const key = date.toISOString().slice(0,10); return { day: shortDay(date), sent: Number(dailyRows.find((row) => row.day === key && row.status === "sent")?.value ?? 0), failed: Number(dailyRows.find((row) => row.day === key && row.status === "failed")?.value ?? 0) }; });
  const growth = Array.from({ length: 6 }, (_, index) => { const date = new Date(); date.setUTCDate(1); date.setUTCMonth(date.getUTCMonth() - (5 - index)); const key = date.toISOString().slice(0,7); return { month: shortMonth(date), users: Number(userGrowth.find((row) => row.month.startsWith(key))?.value ?? 0), workspaces: Number(workspaceGrowth.find((row) => row.month.startsWith(key))?.value ?? 0) }; });
  const stats = [{ label: "Registered users", value: users.value, icon: Users }, { label: "Workspaces", value: workspaces.value, icon: Building2 }, { label: "Requests · 30 days", value: deliveries.value, icon: Activity }, { label: "Accepted email", value: accepted.value, icon: MailCheck }];
  return <div className="flex flex-col gap-8"><header className="flex flex-col justify-between gap-5 lg:flex-row lg:items-end"><div><p className="text-sm font-medium text-primary">Managerial command center</p><h1 className="mt-2 text-3xl font-semibold tracking-tight">Platform overview</h1><p className="mt-2 max-w-2xl text-muted-foreground">Monitor platform health and safely enter customer workflows when operational help is required.</p></div><div className="flex flex-wrap gap-2"><Button variant="outline" render={<Link href="/superadmin/reports" />}><FilePlus2 data-icon="inline-start" />Generate report</Button><Button render={<Link href="/superadmin/users" />}><UserPlus data-icon="inline-start" />Create or manage user</Button></div></header><section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{stats.map(({ label, value, icon: Icon }) => <Card key={label}><CardHeader className="flex flex-row items-center justify-between pb-2"><CardDescription>{label}</CardDescription><Icon className="text-primary" /></CardHeader><CardContent><p className="text-3xl font-semibold tabular-nums">{value}</p></CardContent></Card>)}</section><section className="grid gap-6 xl:grid-cols-2"><Card><CardHeader><CardTitle>Delivery health</CardTitle><CardDescription>Accepted and failed requests over 14 days · UTC · current platform data</CardDescription></CardHeader><CardContent><DeliveryTrendChart data={daily} /></CardContent></Card><Card><CardHeader><CardTitle>Platform growth</CardTitle><CardDescription>New users and workspaces over six calendar months · UTC</CardDescription></CardHeader><CardContent><GrowthChart data={growth} /></CardContent></Card></section><Card><CardHeader className="flex flex-row items-start justify-between gap-4"><div><CardTitle>Recent audit activity</CardTitle><CardDescription>Latest immutable managerial and platform events.</CardDescription></div><Button variant="outline" size="sm" render={<Link href="/superadmin/audit-logs" />}>View audit log</Button></CardHeader><CardContent className="flex flex-col gap-3">{events.length ? events.map((event) => <div key={event.id} className="flex items-center justify-between gap-4 rounded-lg border p-3"><div><p className="font-medium">{event.description}</p><p className="text-xs text-muted-foreground">{event.actorEmail} · {event.createdAt.toLocaleString()}</p></div><Badge variant="secondary">{event.action}</Badge></div>) : <p className="py-10 text-center text-sm text-muted-foreground">No audit events recorded yet.</p>}</CardContent></Card></div>;
}
